### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
**Warning:** This PR contains breaking changes.

In v0.14, Fluentd core developers do not recommend to rewrite tag for routing.
If you want to use tag for routing, please revert fbd364e and b83fbcf.

### CODE REVIEW

**Comment by shun0102** [comment]
Thank you for your PR, and sorry for the late reply.
This PR contains breaking changes.So, I merge other PRs #16 #17 before this PR.
#17 remove dependency of fluent-plugin-rewrite-tag-name.
Please re-send the PR If there is still a need to be fix.

**Comment by cosmo0920** [comment]
Ok. I'll try to rebase to take in required changes.

**Comment by cosmo0920** [comment]
I've tried to rebase at current master and take in required changes.
Could you take a look again?

**Comment by shun0102** [comment]
This code seems good.
However, the conflict occurred,  because I merged #18 .

In addition to it, since this code does not work in v0.12, I want to wait for td-agent 3 to be released which includes v0.14 and I think it is better to add to the README that it does now work on  v0.12.

**Comment by cosmo0920** [comment]
> However, the conflict occurred, because I merged #18 .

Thanks for noticing it.
I'll resolve conflicts.

> In addition to it, since this code does not work in v0.12, I want to wait for td-agent 3 to be released which includes v0.14 and I think it is better to add to the README that it does now work on v0.12.

I think that we don't have to wait td-agent3 release.
Because td-agent has already handling Gemfile feature with `--gemfile` option.
And I think that adding requirement section is enough for both of td-agent2 users and early Fluent v0.14 users.
How do you think of that?

**Comment by cosmo0920** [comment]
I've rebased at current master and pushed with `-f`.

Umm, how about release `.rc` version like as [fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3) and [fluent-plugin-influxdb](https://github.com/fangli/fluent-plugin-influxdb)?

**Comment by cosmo0920** [comment]
Fluentd v0.14 has been reached stable now.
https://www.fluentd.org/blog/fluentd-v0.14.22-has-been-released
Any progress?

**Comment by okkez** [comment]
@shun0102 Do you have enough time to keep maintaining this plugin?
If no, we can take over ownership or become co-maintainers.
See https://github.com/fluent-plugins-nursery/contact

**Comment by okkez** [comment]
Could you add me and @cosmo0920 to this project to collaborators?
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

And could you add me and @cosmo0920 to gem owner? (If you want us to release a new version.)
See [procedure](https://github.com/fluent-plugins-nursery/contact#procedure) No.4. for adding me to gem owner.

**Comment by shun0102** [comment]
Hi, I added @cosmo0920 to collaborators of this project and the gem owner.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
